const userMeta = {
  name: "Shubham",
  summary:
    "Frontend Developer with [experienceYears]+ years of experience in creating and developing innovative web applications. My background includes building AI-driven content platforms, contributing to music streaming services, and leading teams in high-impact projects.",
  journeyStartDate: "2021-09-13",
  myStory:
    "I’m Shubham Bhagwan Salunkhe, a dedicated Frontend Developer with over [experienceYears]+ years of experience in building innovative, scalable, and user-centered web applications. After graduating in 2019, I’ve honed my skills in frontend technologies and have good understanding of backend architectures and database management. At GoPhygital, I’ve contributed significantly to the development of AI-driven platforms for global brands like Mastercard, Mercedes-Benz, Vodafone, Shell and many more, with a focus on cutting-edge features like text-to-speech functionality and real-time content creation tools. My passion for coding is matched by my commitment to team collaboration, having successfully mentored colleagues and streamlined development processes. Whether developing custom ECommerce solutions or creating dynamic, interactive user interfaces, I am always driven by the goal to build seamless, efficient, and impactful digital experiences. I believe in continuous learning and strive to deliver high-quality solutions that address real-world challenges.",
  testimonials: [
    {
      authorTitle: "Team Lead",
      authorSubtitle: "Gophygital",
      gender: "F",
      comment:
        "Shubham has delivered exceptional work, learns quickly, and has strong problem-solving skills. His contribution to Musically, has been highly valuable. He is always helpful, often supporting teammates even when occupied with his own work. He is enthusiastic about learning new technologies and is enjoying his current project. He takes ownership of tasks and works independently when needed. To grow further, he should avoid making hasty decisions and aim for a healthy balance between financial satisfaction and his own work satisfaction. At times, he gets influenced by external factors, which may lead to impulsive choices. Focusing on stability, consistency, and deepening his core knowledge will strengthen his overall development and impact within the team.",
    },
    {
      authorTitle: "Founder and Evangelist",
      authorSubtitle: "Gophygital",
      gender: "M",
      comment: "Keep doing great work.",
    },
    {
      authorTitle: "Human Resources Manager",
      authorSubtitle: "Gophygital",
      gender: "F",
      comment:
        "Shubham has consistently demonstrated exceptional performance throughout the period. He is proactive and self-motivated individual who shows a strong commitment to continuous self-development. His positive attitude, collaborative nature, and willingness to support team members in achieving common goals have made a significant impact on team morale and productivity.",
    },
  ],
  experiences: [
    {
      title: "Senior Frontend Developer",
      subtitle: "GoPhygital Private Limited",
      date: "Sept 2021 - Present",
      imageArr: [
        "images/creation-station.png",
        "images/sonic_space_browse_page.png",
        "images/sonic_space_similar_search.png",
        // "images/sonic_space_track_detail.png",
      ],
      description: [
        "Architected a cutting-edge AI-driven content generation system for leading global brands like Mastercard, Mercedes Benz, Vodafone, Shell and many more, resulted in enhanced creative workflow efficiencies measured at 15% during initial user feedback sessions.",
        "Implemented advanced text-to-speech functionality with 2400+ voice profiles, offensive content detection, and timeline-based voice placement.",
        "Integrated AI tools enabling real-time track creation, remixing with over 10+ customizable parameters, contributed directly to a marked increase in user-generated content by more than 500 unique tracks monthly.",
        "Leveraged OpenAI for generating track names, descriptions, and visually appealing cover images, and Processed more than 500 audio and video files each month with FFmpeg while implementing advanced features like merging tracks seamlessly and applying fade effects to create high-quality sound outputs for users.",
        "Built a music streaming platform integrating Algolia search, Spotify APIs, Cyanite analytics, similarity search, personalized playlist, curated recommendations and track trimming.",
        "Created an admin panel for efficient asset uploads, user management, reporting, and monitoring, reducing administrative overhead by 40%.",
        "Delivered lightweight AI-based applications for Coca-Cola and Mastercard, achieving 95% customer satisfaction on tailored deliverables.",
        "Engineered a unified, scalable codebase supporting multi-brand theming, feature toggles, localized components and reducing production errors by 50%.",
        "Played a leading role in the project, contributing 85% of the frontend development over 3+ years.",
        "Mentored 6+ team members in best practices, enhancing code quality and accelerating project timelines by 25%.",
      ],
      tools: [
        "HTML",
        "CSS",
        "JavaScript",
        "React",
        "Redux",
        "Spring Boot",
        "React Native",
        "MySQL",
        "Git",
        "FFmpeg",
        "Algolia",
        "OpenAI",
        "Tuney's AI",
        "Responsive UI",
      ],
    },
  ],
  // experiences: [
  //   {
  //     title: "Senior Frontend Developer",
  //     subtitle: "GoPhygital Private Limited",
  //     date: "Sept 2021 - Present",
  //     projects: [
  //       {
  //         projectTitle: "AI-Based Content Creation Platform",
  //         imageArr: [
  //           "images/creation-station.png",
  //           "images/sonic_space_browse_page.png",
  //           "images/sonic_space_similar_search.png",
  //           // "images/sonic_space_track_detail.png",
  //         ],
  //         description: [
  //           "Designed and developed an AI-driven content creation platform for top-tier clients such as Mastercard, Mercedes-Benz, Vodafone, and Shell.",
  //           "Implemented advanced text-to-speech functionality with 1800+ voice profiles, including offensive content detection and timeline-based voice placement for dynamic adjustments.",
  //           "Built AI-powered music tools enabling track creation, remixing, instrument edits, and precise drop placements.",
  //           "Leveraged OpenAI to generate dynamic track names, descriptions, and visually appealing cover images.",
  //           "Utilized FFmpeg for advanced merging audio/video files, applying custom fade effects, and executing track trimming.",
  //           "Played a leading role in the project, contributing 85% of the frontend development over two years.",
  //         ],
  //         tools: [
  //           "HTML",
  //           "CSS",
  //           "JavaScript",
  //           "React",
  //           "Redux",
  //           "Spring Boot",
  //           "React Native",
  //           "MySQL",
  //           "Git",
  //           "FFmpeg",
  //           "Algolia",
  //           "OpenAI",
  //           "Tuney's AI",
  //           "Responsive UI",
  //         ],
  //       },
  //       {
  //         projectTitle: "",
  //         imageArr: [
  //           "images/creation-station.png",
  //           "images/sonic_space_browse_page.png",
  //           "images/sonic_space_similar_search.png",
  //           // "images/sonic_space_track_detail.png",
  //         ],
  //         description: [
  //           "Architected a cutting-edge AI-driven content generation system for leading global brands like Mastercard, Mercedes Benz, Vodafone, Shell and many more, resulted in enhanced creative workflow efficiencies measured at 15% during initial user feedback sessions.",
  //           "Implemented advanced text-to-speech functionality with 2400+ voice profiles, offensive content detection, and timeline-based voice placement.",
  //           "Integrated AI tools enabling real-time track creation, remixing with over 10+ customizable parameters, contributed directly to a marked increase in user-generated content by more than 500 unique tracks monthly.",
  //           "Leveraged OpenAI for generating track names, descriptions, and visually appealing cover images, and Processed more than 500 audio and video files each month with FFmpeg while implementing advanced features like merging tracks seamlessly and applying fade effects to create high-quality sound outputs for users.",
  //           "Built a music streaming platform integrating Algolia search, Spotify APIs, Cyanite analytics, similarity search, personalized playlist, curated recommendations and track trimming.",
  //           "Created an admin panel for efficient asset uploads, user management, reporting, and monitoring, reducing administrative overhead by 40%.",
  //           "Delivered lightweight AI-based applications for Coca-Cola and Mastercard, achieving 95% customer satisfaction on tailored deliverables.",
  //           "Engineered a unified, scalable codebase supporting multi-brand theming, feature toggles, localized components and reducing production errors by 50%.",
  //           "Played a leading role in the project, contributing 85% of the frontend development over 3+ years.",
  //           "Mentored 6+ team members in best practices, enhancing code quality and accelerating project timelines by 25%.",
  //         ],
  //         tools: [
  //           "HTML",
  //           "CSS",
  //           "JavaScript",
  //           "React",
  //           "Redux",
  //           "Spring Boot",
  //           "React Native",
  //           "MySQL",
  //           "Git",
  //           "FFmpeg",
  //           "Algolia",
  //           "OpenAI",
  //           "Tuney's AI",
  //           "Responsive UI",
  //         ],
  //       },
  //       {
  //         projectTitle: "",
  //         imageArr: [
  //           "images/creation-station.png",
  //           "images/sonic_space_browse_page.png",
  //           "images/sonic_space_similar_search.png",
  //           // "images/sonic_space_track_detail.png",
  //         ],
  //         description: [
  //           "Architected a cutting-edge AI-driven content generation system for leading global brands like Mastercard, Mercedes Benz, Vodafone, Shell and many more, resulted in enhanced creative workflow efficiencies measured at 15% during initial user feedback sessions.",
  //           "Implemented advanced text-to-speech functionality with 2400+ voice profiles, offensive content detection, and timeline-based voice placement.",
  //           "Integrated AI tools enabling real-time track creation, remixing with over 10+ customizable parameters, contributed directly to a marked increase in user-generated content by more than 500 unique tracks monthly.",
  //           "Leveraged OpenAI for generating track names, descriptions, and visually appealing cover images, and Processed more than 500 audio and video files each month with FFmpeg while implementing advanced features like merging tracks seamlessly and applying fade effects to create high-quality sound outputs for users.",
  //           "Built a music streaming platform integrating Algolia search, Spotify APIs, Cyanite analytics, similarity search, personalized playlist, curated recommendations and track trimming.",
  //           "Created an admin panel for efficient asset uploads, user management, reporting, and monitoring, reducing administrative overhead by 40%.",
  //           "Delivered lightweight AI-based applications for Coca-Cola and Mastercard, achieving 95% customer satisfaction on tailored deliverables.",
  //           "Engineered a unified, scalable codebase supporting multi-brand theming, feature toggles, localized components and reducing production errors by 50%.",
  //           "Played a leading role in the project, contributing 85% of the frontend development over 3+ years.",
  //           "Mentored 6+ team members in best practices, enhancing code quality and accelerating project timelines by 25%.",
  //         ],
  //         tools: [
  //           "HTML",
  //           "CSS",
  //           "JavaScript",
  //           "React",
  //           "Redux",
  //           "Spring Boot",
  //           "React Native",
  //           "MySQL",
  //           "Git",
  //           "FFmpeg",
  //           "Algolia",
  //           "OpenAI",
  //           "Tuney's AI",
  //           "Responsive UI",
  //         ],
  //       },
  //     ],
  //   },
  // ],
  projects: [
    {
      title: "Aimer Candles",
      subtitle: "ECommerce Website + PWA",
      date: "Jan 2025 - Apr 2025",
      image: "images/aimer-candles.netlify.app_.png",
      link: "https://aimer-candles.netlify.app",
      githubLink: "",
      description: [
        "Progressive Web App (PWA): Installable as an app for a seamless, native-like experience.",
        "Secure Authentication: Firebase Authentication for safe login and registration",
        "Responsive Design: Optimized for all screen sizes and devices.",
        "Dynamic Theme: Toggle between dark and light modes for personalized browsing.",
        "Product and Collection Management: Display of products and collections with categorized views, showcasing New Arrivals and Best Sellers section.",
        "Product Filters: Advanced filtering by categories, New Arrivals , and more for quick search.",
        "Cart System: State-managed cart functionality using Redux.",
        "Content Integration: Integrated blog section for sharing product stories, tips, and updates.",
        "Performance Optimized: Fast-loading, offline support, and scalable architecture.",
      ],
      tools: ["HTML", "Tailwind CSS", "React", "Redux", "Responsive UI", "PWA"],
    },
    {
      title: "ReadMe",
      subtitle: "News Website",
      date: "Feb 2024 - Mar 2024",
      image: "images/readme-news.netlify.app_.png",
      link: "https://readme-news.netlify.app",
      githubLink: "https://github.com/shubhamsalunkhe16/readme_news",
      description: [
        "News Feed: Used fake news API for demonstration purposes to fetch news from various categories (e.g. technology, business, sports, etc.).",
        "Category Filtering: Users can browse news based on predefined categories.",
        "Dark/Light Mode: Integrated themes for user comfort.",
        "Responsive Design: Fully optimized for desktops, tablets, and mobile devices.",
        "Article Previews: Compact cards display headline, image, and brief description.",
        "Add to Home Screen: Install the app on any device for a native-like experience.",
      ],
      tools: [
        "HTML",
        "Tailwind CSS",
        "React",
        "TanStack Query",
        "Mobile-Friendly Design",
      ],
    },
    {
      title: "Let's Bet",
      subtitle: "Auto-Play Game",
      date: "Aug 2023 - Sep 2023",
      image: "images/lets-bet-2.png",
      link: "https://lets-bet.netlify.app/",
      githubLink: "https://github.com/shubhamsalunkhe16/lets-bet",
      description: [
        "Immerse yourself in the world of fun with our web-based betting app, designed purely for entertainment.",
        "Choose your IPL team and watch the scores generate automatically.",
        "We've crafted a user-friendly interface and included interactive graphs for a captivating visual experience.",
        "May your team thrive, and good luck! Enjoy the game to the fullest!",
      ],
      tools: ["HTML", "CSS", "Javascript", "React"],
    },
    {
      title: "HoliDazzle",
      subtitle: "Static Website",
      date: "Nov 2021 - Dec 2021",
      image: "images/Holidazzle.png",
      link: "https://lets-bet.netlify.app/",
      githubLink: "https://github.com/shubhamsalunkhe16/Holidazzle",
      description: [
        "Crafted a captivating Travel Web-design project utilizing the power of HTML, CSS, JS, and Bootstrap.",
        "Developed a fully responsive website comprising of four meticulously designed pages.",
      ],
      tools: ["HTML", "CSS", "Javascript", "Bootstrap"],
    },
  ],
  skillMeta: [
    {
      title: "Frontend",
      description:
        "Frontend is the user-facing part of a website, built for design and interactivity.",
      skills: [
        "HTML",
        "CSS",
        "Sass",
        "Tailwind CSS",
        "JavaScript",
        "jQuery",
        "TypeScript",
        "React",
        "Redux",
        "Next.js",
      ],
    },
    {
      title: "Backend",
      description:
        "Backend is the server-side part of a website or app, managing data, logic, and APIs.",
      skills: ["Node.js", "Java", "Python"],
    },
    {
      title: "Databases",
      description:
        "A database is a structured system for storing, managing, and retrieving data.",
      skills: ["MySQL", "MongoDB", "Firebase"],
    },
  ],
  socialLinks: {
    linkedin: "https://www.linkedin.com/in/shubhamsalunkhe16/",
    github: "https://github.com/shubhamsalunkhe16",
    instagram:
      "https://www.instagram.com/salunkheshubham16?igsh=dnJzaG9kaHFsZjRn",
  },
};

export default userMeta;
